import { Metadata } from "next";

export const metadata: Metadata = {
  title: "기업 문의",
  description: "Generated by create next app",
};
function ContactEnterprisePage() {
  return <div>기업 문의</div>;
}
export default ContactEnterprisePage;
