import { Metadata } from "next";

export const metadata: Metadata = {
  title: "수강생",
  description: "Generated by create next app",
};
function StudentPage() {
  return <div>StudentPage</div>;
}
export default StudentPage;
