import { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import IntroduceCard from "./components/IntroduceCard";

export const metadata: Metadata = {
  title: "탤런트 상세 페이지",
  description: "Generated by create next app",
};

export default function TalentDetailPage() {
  return (
    <div className="w-full text-black mt-8">
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
        {/* 왼쪽: 이전 페이지 (Link 사용) */}
        <Link href="/talents" className="flex items-center gap-1 hover:opacity-80 transition">
          <Image src="/icons/outline-cheveron-left.svg" alt="back" width={24} height={24} />
          <span className="text-lg font-bold text-black">이전 페이지</span>
        </Link>

        {/* 가운데 제목 */}
        <h1 className="absolute left-1/2 -translate-x-1/2 text-lg font-bold text-black">
          인재 상세 페이지
        </h1>
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <IntroduceCard
          name="유한성"
          phone="010 0000 0000"
          email="dfdfds@naver.com"
          university="한국대"
          major="소프트웨어"
          job="프론트엔드"
          jobGroup="개발"
          badges={[
            { label: "부트캠프 수료자", type: "bootcamp" },
            { label: "창업 경험자", type: "startup" },
            { label: "자격증 보유자", type: "certified" },
            { label: "전공자", type: "major" },
          ]}
          tendencies={[
            "제너럴 리스트형",
            "속도형",
            "수직적 문화형",
            "과정 중심형",
            "현실주의형",
            "워터폴형",
            "애자일형",
            "리더형",
            "창의형",
            "결과 중심형",
          ]}
          skills={["JavaScript", "TypeScript", "React", "Next.js", "Tailwind CSS", "Zustand"]}
        />
      </div>
    </div>
  );
}
