import { Metadata } from "next";

export const metadata: Metadata = {
  title: "탤런트 상세 페이지",
  description: "Generated by create next app",
};
export default function TalentDetailPage() {
  return <div>TalentDetailPage</div>;
}
