import { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import IntroduceCard from "./_components/IntroduceCard";
import ResumeCard from "./_components/ResumeCard";
import PortfolioCard from "./_components/PorfolioCard";

export const metadata: Metadata = {
  title: "탤런트 상세 페이지",
  description: "Generated by create next app",
};

export default function TalentDetailPage() {
  const resumeData = {
    summary: "문제 해결과 UI/UX 개선에 집중하는 프론트엔드 개발자입니다.",
    education: {
      school: "숭실대학교",
      start: "2018.03",
      end: "2024.02",
      major: "소프트웨어",
      graduate: "졸업",
      note: "이것저것 했습니다.",
    },
    careers: [
      {
        company: "OOO 스타트업",
        start: "2023.01",
        end: "2024.10",
        deptOrTeam: "프론트엔드팀",
        title: "프론트엔드 엔지니어",
        rank: "인턴",
        desc: "Next.js 15 + Tailwind 기반의 SPA 구축 및 성능 최적화 담당.",
      },
    ],
    awards: [
      { title: "해커톤 장려상", start: "2022.07", end: "2022.07", desc: "팀 프로젝트 수행" },
    ],
    languages: [{ name: "TOEIC", start: "2020.01", end: "현재" }],
    certificates: [{ name: "정보처리기사", start: "2022.06", end: "2022.06" }],
    links: [{ url: "https://github.com/gyuwonlee" }, { url: "https://gyuwon.dev" }],
  };

  return (
    <div className="w-full text-black mt-8">
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
        {/* 왼쪽: 이전 페이지 (Link 사용) */}
        <Link href="/talents" className="flex items-center gap-1 hover:opacity-80 transition">
          <Image src="/icons/outline-cheveron-left.svg" alt="back" width={24} height={24} />
          <span className="text-lg font-bold text-black">이전 페이지</span>
        </Link>

        {/* 가운데 제목 */}
        <h1 className="absolute left-1/2 -translate-x-1/2 text-lg font-bold text-black">
          인재 상세 페이지
        </h1>
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <IntroduceCard
          name="이규원"
          phone="010 5226 9456"
          email="woni0114@naver.com"
          university="숭실대"
          major="소프트웨어"
          job="프론트엔드"
          jobGroup="개발"
          badges={[
            { label: "부트캠프 수료자", type: "bootcamp" },
            { label: "창업 경험자", type: "startup" },
            { label: "자격증 보유자", type: "certified" },
            { label: "전공자", type: "major" },
          ]}
          tendencies={[
            "제너럴 리스트형",
            "속도형",
            "수직적 문화형",
            "과정 중심형",
            "현실주의형",
            "워터폴형",
            "애자일형",
            "리더형",
            "창의형",
            "결과 중심형",
          ]}
          skills={["JavaScript", "TypeScript", "React", "Next.js", "Tailwind CSS", "Zustand"]}
        />
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <ResumeCard {...resumeData} />
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <PortfolioCard fileName="frontend-portfolio.pdf" fileUrl="/files/frontend-portfolio.pdf" />
      </div>
    </div>
  );
}
