import { Metadata } from "next";

export const metadata: Metadata = {
  title: "탤런트 목록 페이지",
  description: "Generated by create next app",
};
function TalentsPage() {
  return <div>page</div>;
}
export default TalentsPage;
