import { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import IntroduceCard from "./_components/IntroduceCard";
import ResumeCard from "./_components/ResumeCard";
import PortfolioCard from "./_components/PorfolioCard";

export const metadata: Metadata = {
  title: "탤런트 상세 페이지",
  description: "Generated by create next app",
};

export default function TalentDetailPage() {
  const resumeData = {
    summary:
      "저는 문제를 해결하며 가치를 창출하는 개발자를 꿈꾸는 컴퓨터공학 전공자입니다. 학부 시절 자료구조와 운영체제 과목을 통해 프로그래밍의 기본기를 다졌고, 졸업 후 **‘멋쟁이사자처럼 부트캠프’**에 참여하여 실무 중심의 개발 역량을 쌓았습니다.멋쟁이 사자처럼 부트캠프에서 진행한 **“OOO 서비스 개발 프로젝트”**에서는 백엔드 개발자로 참여하여 Node.js 기반의 RESTful API를 설계하고, JWT 인증 시스템과 AWS EC2·S3를 이용한 배포 환경을 구축했습니다. 이 경험을 통해 서비스 기획부터 배포까지의 전체 개발 프로세스를 이해하게 되었으며, 팀 내 코드 리뷰와 협업 툴(Git, Notion, Slack)을 활용하며 실무형 협업 능력을 길렀습니다. 저의 강점은 끊임없이 학습하고 개선하는 태도입니다. 에러가 발생하면 단순히 수정에 그치지 않고 원인을 분석하여 블로그에 기록하며, 재발 방지를 위한 대안을 제시합니다. 또한 새로운 기술이 등장하면 공식 문서를 기반으로 직접 실습해보며 실무에 적용할 방법을 탐색합니다. 귀사는 사용자 중심의 서비스와 기술적 완성도를 동시에 추구한다는 점에서 저의 성장 방향과 일치합니다. 입사 후에는 빠르게 팀의 개발 환경에 적응하여 안정적인 시스템 구현과 코드 품질 개선에 기여하겠습니다. 나아가 사용자의 문제를 기술로 해결하는 개발자로 성장하며, 회사의 발전과 함께 성장하고 싶습니다",
    education: {
      school: "숭실대학교",
      start: "2018.03",
      end: "2024.02",
      major: "소프트웨어",
      graduate: "졸업",
      note: "이것저것 했습니다.",
    },
    careers: [
      {
        company: "OOO 스타트업",
        start: "2023.01",
        end: "2024.10",
        deptOrTeam: "프론트엔드팀",
        title: "프론트엔드 엔지니어",
        desc: "Next.js 15 + Tailwind 기반의 SPA 구축 및 성능 최적화 담당.",
      },
    ],
    awards: [
      { title: "해커톤 장려상", start: "2022.07", end: "2022.07", desc: "팀 프로젝트 수행" },
    ],
    languages: [{ name: "TOEIC", start: "2020.01", end: "현재" }],
    certificates: [{ name: "정보처리기사", start: "2022.06", end: "2022.06" }],
    links: [{ url: "https://github.com/gyuwonlee" }, { url: "https://gyuwon.dev" }],
  };

  return (
    <div className="w-full text-black mt-8">
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
        {/* 왼쪽: 이전 페이지 (Link 사용) */}
        <Link href="/talents" className="flex items-center gap-1 hover:opacity-80 transition">
          <Image src="/icons/outline-cheveron-left.svg" alt="back" width={24} height={24} />
          <span className="text-lg font-bold text-black">이전 페이지</span>
        </Link>

        {/* 가운데 제목 */}
        <h1 className="absolute left-1/2 -translate-x-1/2 text-lg font-bold text-black">
          인재 상세 페이지
        </h1>
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <IntroduceCard
          name="이규원"
          phone="010 5226 9456"
          email="woni0114@naver.com"
          university="숭실대"
          major="소프트웨어"
          job="프론트엔드"
          jobGroup="개발"
          badges={[
            { label: "부트캠프 수료자", type: "bootcamp" },
            { label: "창업 경험자", type: "startup" },
            { label: "자격증 보유자", type: "certified" },
            { label: "전공자", type: "major" },
          ]}
          tendencies={[
            "제너럴 리스트형",
            "속도형",
            "수직적 문화형",
            "과정 중심형",
            "현실주의형",
            "워터폴형",
            "애자일형",
            "리더형",
            "창의형",
            "결과 중심형",
          ]}
          skills={["JavaScript", "TypeScript", "React", "Next.js", "Tailwind CSS", "Zustand"]}
        />
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <ResumeCard {...resumeData} />
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <PortfolioCard fileName="frontend-portfolio.pdf" fileUrl="/files/frontend-portfolio.pdf" />
      </div>
    </div>
  );
}
