import { Metadata } from "next";

export const metadata: Metadata = {
  title: "관리자",
  description: "Generated by create next app",
};
function AdminPage() {
  return <div>page</div>;
}
export default AdminPage;
