import Footer from "@/components/Footer";
import { Metadata } from "next";
import BusinessConnect from "./_components/BusinessConnect";
import HeroSection from "./_components/HeroSection";
import BenefitsSection from "./_components/BenefitsSection";
import ProgramStatsSection from "./_components/ProgramStatsSection";
import UniversityGridSection from "./_components/UniversityGridSection";
import StartupsSection from "./_components/StartupsSection";
import CompanyLogosSection from "./_components/CompanyLogosSection";

export const metadata: Metadata = {
  title: "랜딩페이지",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <HeroSection />
      <BenefitsSection />
      <ProgramStatsSection />
      <UniversityGridSection />
      <StartupsSection />
      <CompanyLogosSection />
      <BusinessConnect />
      <Footer />
    </main>
  );
}
