import { Metadata } from "next";

export const metadata: Metadata = {
  title: "랜딩페이지",
  description: "Generated by create next app",
};

export default function Home() {
  return <div className="font-en-title text-primary text-3xl">랜딩페이지</div>;
}
