import UserTable from '../_components/UserTable';

// Mock data for demonstration
const mockUsers = [
  {
    id: '1',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'admin' as const,
    hasAdminPermission: true,
    isActive: true,
  },
  {
    id: '2',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '3',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '4',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '5',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '6',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '7',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '8',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '9',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '10',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '11',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '12',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '13',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '14',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
  {
    id: '15',
    name: '유재민',
    company: '멋쟁이사자처럼(기업명)',
    email: '1234@gmail.com',
    joinDate: '2025. 11.25',
    role: 'normalUser' as const,
    hasAdminPermission: false,
    isActive: true,
  },
];

function AdminUsers() {
  return (
    <UserTable users={mockUsers} />
  );
}

export default AdminUsers;
