import { Metadata } from "next";

export const metadata: Metadata = {
  title: "회원가입",
  description: "Generated by create next app",
};
function SignUpPage() {
  return <div>회원가입</div>;
}
export default SignUpPage;
