import { Metadata } from "next";

export const metadata: Metadata = {
  title: "로그인",
  description: "Generated by create next app",
};
function SignInPage() {
  return <div>로그인</div>;
}
export default SignInPage;
